name: torbox-media-center
services:
    torbox-media-center:
        container_name: torbox-media-center
        stdin_open: true
        tty: true
        restart: always
        volumes:
            - /home/$(whoami)/torbox:/torbox
        environment:
            - TORBOX_API_KEY=<input your api key>
            - MOUNT_METHOD=strm
            - MOUNT_PATH=/torbox
            - RAW_MODE=false
            - ENABLE_METADATA=false
            - MOUNT_REFRESH_TIME=slow
            - ENABLE_MEDIA_FETCH=false
            - ENABLE_WANT_API=false
            - MEDIA_FETCH_DEBUG=false
            - TBM_TOOLS_URL=https://tbm.tools
            - AIOSTREAMS_URLS=
            - TMDB_DISCOVER_INTERVAL=1
            - DISCOVER_MOVIES_PER_RUN=6
            - DISCOVER_SERIES_EPISODES_PER_RUN=20
            - DISCOVER_ANIME_EPISODES_PER_RUN=10
            - ENABLE_ANIME_DISCOVER=false
            - WANT_API_PORT=9876
            - ACQUISITION_INTERVAL=5
            - ACQUISITION_HOURLY_BUDGET=36
            - MIN_DOWNLOAD_SPEED_MBS=1
        ports:
            - "9876:9876"
        image: anonymoussystems/torbox-media-center:main
     
